services:
  bass:
    image: natenho/mockaco:1.9.14
    container_name: bass-mockaco
    ports:
      - 6901:5000
    volumes:
      - ./mocks/bass:/app/Mocks:ro
      - ./mocks/cert:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_URLS=http://*:5000
    mem_limit: 124m
    cpus: 0.3

  core-accounts:
    image: natenho/mockaco:1.9.14
    container_name: vulture-pay-core-accounts
    ports:
      - 6902:5000
    volumes:
      - ./mocks/vpay-accounts:/app/Mocks:ro
      - ./mocks/cert:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_URLS=http://*:5000
    mem_limit: 124m
    cpus: 0.3

  core-payments:
    image: leandroalves86/vulture-pay-core-payments:latest
    container_name: vulture-pay-core-payments
    ports:
      - "5123:5123"


  core-antifraud:
    image: leandroalves86/vulture-pay-core-antifraud:latest
    container_name: vulture-pay-core-antifraud

  core-transactional:
    image: leandroalves86/vulture-pay-core-transactional:latest
    container_name: vulture-pay-core-transactional


  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongo-db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"