services:
  bass:
    image: natenho/mockaco:1.9.14
    container_name: bass-mockaco
    ports:
      - 6901:5000
    volumes:
      - ./mocks/bass:/app/Mocks:ro
      - ./mocks/cert:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_URLS=http://*:5000
    mem_limit: 124m
    cpus: 0.3

  core-accounts:
    image: natenho/mockaco:1.9.14
    container_name: vulture-pay-core-accounts
    ports:
      - 6902:5000
    volumes:
      - ./mocks/vpay-accounts:/app/Mocks:ro
      - ./mocks/cert:/https:ro
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_URLS=http://*:5000
    mem_limit: 124m
    cpus: 0.3

  core-payments:
    image: leandroalves86/vulture-pay-core-payments:latest
    container_name: vulture-pay-core-payments
    ports:
      - "5123:5123"


  core-antifraud:
    image: leandroalves86/amqp.mock:1.0.0.beta01
    container_name: vulture-pay-core-antifraud
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
      - Rabbit__UserName=${RABBIT_USERNAME}
      - Rabbit__Password=${RABBIT_PASSWORD}
      - Rabbit__VirtualHost=${RABBIT_VIRTUALHOST}
      - Rabbit__Port=${RABBIT_PORT}
      - Rabbit__HostName=${RABBIT_HOSTNAME}
      - Rabbit__Endpoints__0=${RABBIT_ENDPOINT}
      - Rabbit__Queues__0__ExchangeOrigin=core.antifraud.exchange
      - Rabbit__Queues__0__ExchangeTypeOrigin=direct
      - Rabbit__Queues__0__QueueOrigin=core.antifraud.queue
      - Rabbit__Queues__0__ExchangeDestination=core.payments.saga
      - Rabbit__Queues__0__ExchangeTypeDestination=direct
      - Rabbit__Queues__0__QueuesDestination__0=core.payments.queue.01
      - Rabbit__Queues__0__QueuesDestination__1=core.payments.queue.02


  core-transactional:
    image: leandroalves86/amqp.mock:1.0.0.beta01
    container_name: vulture-pay-core-transactional


  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  mongo-db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"